plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.shadow.automap'
    compileSdk 34

    defaultConfig {
        applicationId "com.shadow.automap"
        minSdk 24
        targetSdk 34
        versionCode 15
        versionName "1.5"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // 添加以下代码来配置 APK 输出名称
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            // 1. 定义 App 名称 (你可以替换成你自己的 App 名字)
            def appName = "AutoMap"

            // 2. 获取版本号 (读取自 defaultConfig 中的 versionName)
            def version = variant.versionName

            // 3. 获取构建类型 (比如 release 或 debug)
            def buildType = variant.buildType.name

            // 4. 获取当前时间 (格式：年月日_时分)
            def releaseTime = new Date().format("yyyyMMdd_HHmm")

            // 5. 拼接最终的文件名
            // 最终效果类似：MyApp_v1.0.0_release_20231027_1530.apk
            def fileName = "${appName}_v${version}_${buildType}_${releaseTime}.apk"

            // 6. 赋值给输出文件名
            outputFileName = fileName
        }
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}